-- Demo data: an invented few months of a two-person household's watch diary
-- and request queue.
--
-- Nothing here is real and nothing here was copied out of any live database.
-- It exists so a fresh clone shows the app doing its actual job (the
-- watchlist-vs-request split, the diary filters, per-person ratings, the
-- "loved" flow, the recap) instead of an empty page, and so the screenshots
-- in the README can be regenerated by anyone.
--
--   make demo          brings the stack up and loads this file
--   make demo-reset    wipes these rows and loads them again
--
-- Safe to run only on a throwaway database: it inserts, it does not merge.
-- tmdb_id values below are invented placeholders, not real TMDB ids; posters
-- are left empty (the templates already fall back to an emoji tile) rather
-- than hotlink real artwork.

begin;

-- --- titles ------------------------------------------------------------
-- Real, well-known titles so the screenshots read as genuine, spanning
-- enough genres and kinds (movie/series) for the diary chips and the
-- recap's genre bars to have something to chew on.

insert into titles (tmdb_id, kind, name, year, poster, runtime_min, genres) values
  (900101, 'movie',  'Dune: Part Two',                      2024, '', 166, 'Science Fiction, Adventure, Drama'),
  (900102, 'movie',  'Oppenheimer',                          2023, '', 180, 'Drama, History, Thriller'),
  (900103, 'series', 'The Bear',                             2022, '',  30, 'Comedy, Drama'),
  (900104, 'series', 'Slow Horses',                          2022, '',  55, 'Drama, Thriller, Comedy'),
  (900105, 'movie',  'Poor Things',                          2023, '', 141, 'Comedy, Drama, Science Fiction'),
  (900106, 'series', 'Shogun',                               2024, '',  60, 'Drama, History, War'),
  (900107, 'series', 'The Last of Us',                       2023, '',  55, 'Drama, Science Fiction, Horror'),
  (900108, 'movie',  'Everything Everywhere All at Once',    2022, '', 140, 'Action, Adventure, Comedy, Science Fiction'),
  (900109, 'series', 'Fallout',                               2024, '',  60, 'Science Fiction, Action, Adventure'),
  (900110, 'movie',  'Barbie',                                2023, '', 114, 'Comedy, Adventure, Fantasy'),
  (900111, 'movie',  'Godzilla x Kong: The New Empire',       2024, '', 115, 'Action, Science Fiction, Adventure'),
  (900112, 'movie',  'Anatomy of a Fall',                     2023, '', 152, 'Drama, Mystery, Crime'),
  (900113, 'series', 'Ted Lasso',                             2020, '',  30, 'Comedy, Drama'),
  (900114, 'movie',  'Interstellar',                          2014, '', 169, 'Adventure, Drama, Science Fiction'),
  -- Requested / watchlist titles: not watched yet, so they show up on the
  -- "Want to watch" tab instead of the diary.
  (900201, 'movie',  'Wicked: For Good',                     2025, '', 137, 'Fantasy, Romance, Musical'),
  (900202, 'series', 'Severance',                             2022, '',  55, 'Drama, Mystery, Science Fiction'),
  (900203, 'movie',  'Furiosa: A Mad Max Saga',               2024, '', 148, 'Action, Adventure, Science Fiction'),
  (900204, 'series', 'House of the Dragon',                   2022, '',  65, 'Drama, Fantasy, Action'),
  (900205, 'movie',  'Twisters',                              2024, '', 122, 'Action, Adventure, Thriller'),
  (900206, 'movie',  'Alien: Romulus',                        2024, '', 119, 'Horror, Science Fiction'),
  (900207, 'series', 'Bridgerton',                             2020, '',  60, 'Drama, Romance')
on conflict (tmdb_id) do nothing;

-- Attended events (concert/sports/travel) carry no tmdb_id: the poller
-- creates these the same way from a calendar event title.
insert into titles (kind, name, year, poster, runtime_min, genres) values
  ('movie', 'Foo Fighters: Everything or Nothing Tour', null, '', 0, ''),
  ('movie', 'Dolphins vs. Bills',                        null, '', 0, ''),
  ('movie', 'Long weekend in Charleston',                null, '', 0, '')
on conflict do nothing;

-- --- the request queue / watchlist ("Want to watch") ---------------------
-- Empty watch_on = a Jellyfin request; a service name = already streamable,
-- added just to remember it. status='available' shows the "on Jellyfin"
-- badge; progress is what the poller would have written for a partial
-- season.

insert into requests (title_id, season, requested_by, status, watch_on, progress, available_at) values
  ((select id from titles where tmdb_id = 900201), null, 'Aline',   'open',      '', '', null),
  ((select id from titles where tmdb_id = 900202), 2,    'Willian', 'open',      '', '4/10 eps', null),
  ((select id from titles where tmdb_id = 900203), null, 'Both',    'available', '', '', now() - interval '3 days'),
  ((select id from titles where tmdb_id = 900204), 2,    'Aline',   'open',      'HBO Max', '', null),
  ((select id from titles where tmdb_id = 900205), null, 'Willian', 'open',      'Peacock', '', null),
  ((select id from titles where tmdb_id = 900206), null, 'Willian', 'open',      '', '', null),
  ((select id from titles where tmdb_id = 900207), 3,    'Both',    'open',      'Netflix', '', null)
on conflict (title_id, coalesce(season, 0)) do nothing;

-- --- the diary ("Watched") ----------------------------------------------
-- A few months' spread across movies, series (per season), a couple of
-- cinema visits, a concert, a sports outing and a trip. Mostly logged as
-- "Both" on purpose (the recap's "Together" majority), with enough solo
-- entries that the per-person split means something. Ratings are
-- per-person; "loved" is the 5-star-plus-heart option, at least one each.

insert into watches (title_id, season, platform, watched_on, who, rating_willian, rating_aline, loved_willian, loved_aline, note) values
  ((select id from titles where tmdb_id = 900109), 1,    'Prime',    '2026-05-28', 'Aline',   null, 4,    false, false, ''),
  ((select id from titles where tmdb_id = 900102), null, 'HBO Max',  '2026-06-01', 'Both',    5,    4,    false, false, ''),
  ((select id from titles where tmdb_id = 900101), null, 'Cinema',   '2026-06-02', 'Both',    5,    5,    true,  true,  'opening weekend, front row'),
  ((select id from titles where tmdb_id = 900103), 3,    'Hulu',     '2026-06-10', 'Willian', 4,    null, false, false, ''),
  ((select id from titles where tmdb_id = 900105), null, 'Peacock',  '2026-06-15', 'Both',    4,    5,    false, false, ''),
  ((select id from titles where tmdb_id = 900106), 1,    'Hulu',     '2026-06-20', 'Both',    5,    5,    false, true,  ''),
  ((select id from titles where tmdb_id = 900110), null, 'HBO Max',  '2026-06-25', 'Both',    4,    4,    false, false, ''),
  ((select id from titles where tmdb_id = 900104), 4,    'AppleTV',  '2026-07-01', 'Both',    5,    4,    true,  false, ''),
  ((select id from titles where tmdb_id = 900107), 2,    'HBO Max',  '2026-07-05', 'Willian', 5,    null, false, false, ''),
  ((select id from titles where tmdb_id = 900108), null, 'Prime',    '2026-07-10', 'Both',    5,    4,    false, false, 'rewatch'),
  ((select id from titles where tmdb_id = 900112), null, 'Netflix',  '2026-07-25', 'Aline',   null, 5,    false, false, ''),
  ((select id from titles where tmdb_id = 900111), null, 'Cinema',   '2026-07-20', 'Both',    3,    3,    false, false, ''),
  ((select id from titles where tmdb_id = 900113), 3,    'AppleTV',  '2026-08-01', 'Both',    4,    4,    false, false, ''),
  ((select id from titles where tmdb_id = 900114), null, 'Jellyfin', '2026-08-05', 'Willian', 5,    null, true,  false, 'rewatch before the sequel news');

insert into watches (title_id, platform, watched_on, who, activity, days) values
  ((select id from titles where name = 'Foo Fighters: Everything or Nothing Tour'), 'Live', '2026-06-08', 'Both',    'concert', 1),
  ((select id from titles where name = 'Dolphins vs. Bills'),                       'Live', '2026-07-14', 'Willian', 'sports',  1),
  ((select id from titles where name = 'Long weekend in Charleston'),              'Live', '2026-07-04', 'Both',    'travel',  3);

commit;

-- Posters, resolved once from TMDB so a fresh clone looks like the real thing
-- instead of a wall of placeholders. These are the same public image URLs the
-- app itself stores when it matches a title, and they are served by TMDB's CDN
-- (their terms ask for attribution, which the README gives). Nothing here is
-- private: they are cover images for well known films and series.
update titles t set poster = v.url
from (values
  ('Dune: Part Two', 'https://image.tmdb.org/t/p/w342/6izwz7rsy95ARzTR3poZ8H6c5pp.jpg'),
  ('Oppenheimer', 'https://image.tmdb.org/t/p/w342/8Gxv8gSFCU0XGDykEGv7zR1n2ua.jpg'),
  ('The Bear', 'https://image.tmdb.org/t/p/w342/eKfVzzEazSIjJMrw9ADa2x8ksLz.jpg'),
  ('Slow Horses', 'https://image.tmdb.org/t/p/w342/5RuZZIouptatjV96BdPmKmRsnGg.jpg'),
  ('Poor Things', 'https://image.tmdb.org/t/p/w342/kCGlIMHnOm8JPXq3rXM6c5wMxcT.jpg'),
  ('Shogun', 'https://image.tmdb.org/t/p/w342/7O4iVfOMQmdCSxhOg1WnzG1AgYT.jpg'),
  ('The Last of Us', 'https://image.tmdb.org/t/p/w342/dmo6TYuuJgaYinXBPjrgG9mB5od.jpg'),
  ('Everything Everywhere All at Once', 'https://image.tmdb.org/t/p/w342/u68AjlvlutfEIcpmbYpKcdi09ut.jpg'),
  ('Fallout', 'https://image.tmdb.org/t/p/w342/c15BtJxCXMrISLVmysdsnZUPQft.jpg'),
  ('Barbie', 'https://image.tmdb.org/t/p/w342/iuFNMS8U5cb6xfzi51Dbkovj7vM.jpg'),
  ('Godzilla x Kong: The New Empire', 'https://image.tmdb.org/t/p/w342/z1p34vh7dEOnLDmyCrlUVLuoDzd.jpg'),
  ('Anatomy of a Fall', 'https://image.tmdb.org/t/p/w342/1ho0d4LNZw3Y0voeKmSvPSgJOJ2.jpg'),
  ('Ted Lasso', 'https://image.tmdb.org/t/p/w342/uRHsiw1wLxPHFXkkv4Ix1s0O6f4.jpg'),
  ('Interstellar', 'https://image.tmdb.org/t/p/w342/yQvGrMoipbRoddT0ZR8tPoR7NfX.jpg'),
  ('Wicked: For Good', 'https://image.tmdb.org/t/p/w342/si9tolnefLSUKaqQEGz1bWArOaL.jpg'),
  ('Severance', 'https://image.tmdb.org/t/p/w342/pPHpeI2X1qEd1CS1SeyrdhZ4qnT.jpg'),
  ('Furiosa: A Mad Max Saga', 'https://image.tmdb.org/t/p/w342/iADOJ8Zymht2JPMoy3R7xceZprc.jpg'),
  ('House of the Dragon', 'https://image.tmdb.org/t/p/w342/7V0Ebks0GgpKvQ7QbLAIdX5dos4.jpg'),
  ('Twisters', 'https://image.tmdb.org/t/p/w342/pjnD08FlMAIXsfOLKQbvmO0f0MD.jpg'),
  ('Alien: Romulus', 'https://image.tmdb.org/t/p/w342/2uSWRTtCG336nuBiG8jOTEUKSy8.jpg')
) as v(name, url)
where t.name = v.name;

update titles set poster = 'https://image.tmdb.org/t/p/w342/uXTg565ahu9RwonCX1V2Hex1NU6.jpg'
  where name = 'Bridgerton';
